name: Directory

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    env: 
      project: ./dbz
    steps:
    - name: Checkout
      uses: actions/checkout@v2
#       working-directory: ./dbz
      
#     - name: MKDIR & CD
#       run: |
#         pwd # /home/runner/work/try/try
#         mkdir hello
#         cd hello
#         pwd # /home/runner/work/try/try/hello
    - name: WORKING DIRECTORY
      env: 
        project: "./dbz"
      run: echo "HELLO WORLD"
      working-directory: ${{env.project}}
        
#     - name: WORKING DIRECTORY
#       working-directory: $project_dir
#       run: |
#         pwd
#         echo "HERE: $project_dir"
#       env: 
#         project_dir: "./dbz"
    
