name: Download Workflow Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to

    steps:
    - name: Download Workflow Artifact
      uses: dawidd6/action-download-artifact@v2
      continue-on-error: true 
      with:
        github_token: ${{secrets.GH_TOKEN}}
        # Required, workflow file name or ID
        workflow: foo.yml # project name
        
        # SELECTOR
        # Optional, the conclusion of a completed workflow to search for
        # Can be one of:
        # "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Ignores conclusion by default (thus using the most recent completed run when no other option is specified, regardless of conclusion)
        workflow_conclusion: success
        
        # RESEARCH
        # Optional, uploaded artifact name, will download all artifacts if not specified and extract them in respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        name: freestyle-raven

        # TARGET DIRECTORY || nil
        # Optional, directory where to extract artifact
        path: cagedstyle-raven
#         repo: rogerprz/WorkflowTesting
    - name: Copy Files
      run: |
        echo "HERE:${{ github.temp }}"
        cp -r ${{ github.temp }}/freestyle-raven/**.txt ${{ github.workspace }}/
