name: Doxygen Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Doxygen
      uses: mattnotmitt/doxygen-action@v1
      #with:
       # doxyfile-path: ./Doxyfile
 
