name: Echo if test

on: workflow_dispatch

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to

    steps:
    - name: run command
      shell: bash
      run: echo "hey there"
      if:
    - name: run command two
      shell: bash
      run: echo "number two"
      if:
    
