name: ADO Gradle

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew.bat build -DProp=value
        working-directory: ./test-gradle
        
