name: ADO ArchiveFiles

on: workflow_dispatch

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Action Zip
      uses: papeloto/action-zip@v1
      with:
        files: archive
        dest: archive.zip

    - name: 7z files
      run: 7z u -mx=9 archive.7z archive
      if: success() || failure()
    - name: Tar files
      run: tar -cf archive.tar archive
      if: success() || failure()
    - name: ZIP files
      run: zip -r -u archive.zip archive
      if: success() || failure()
      
   
