name: AzWebApp
on: workflow_dispatch
jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: Azure/login@v1
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    - uses: Azure/webapps-deploy@v2
      with:
        app-name: test-az-funct
        package: "${{ github.workspace }}/**/*.zip"
