name: ADO Azure CLI

on: workflow_dispatch
jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Run Start Azure App Service
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az account show
          az webapp stop --name valet-app --resource-group valet-azure-resource-group
