name: dependsOn-Job-17
on: workflow_dispatch

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo "hello"
  B:
    needs:
    - A
    runs-on: ubuntu-latest
    if: needs.A.result == 'Success'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo this will run when A runs and succeeds
  C:
    needs:
    - A
    runs-on: ubuntu-latest
    if: needs.A.result == 'success'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo this will run when A runs and succeeds
  D:
    needs:
    - A
    runs-on: ubuntu-latest
    if: failure() &&  needs.A.result == 'success'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo this will run when A runs and succeeds


#  C:
#    needs:
#    - A
#    runs-on: ubuntu-latest
#    steps:
#    - name: checkout
#      uses: actions/checkout@v2
#    - run: |
#       echo w_result:${{ needs.A.result }}
#       echo no_result:${{ needs.A }}
