name: dependsOn-Job-17
on: workflow_dispatch
jobs:
  A:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo "Hello"
  C:
   needs:
   - A
   runs-on: ubuntu-latest
   steps:
   - name: checkout
     uses: actions/checkout@v2
   - run: |
      "echo w_result:${{ needs.A.result }}"
      "echo no_result:${{ needs.A }}"
      "echo eq_succ_():${{ needs.A.result == success() }}"
      "echo eq_succ_no_():${{ needs.A.result == success }}"
       "echo eq_str:${{ needs.A.result == success }} "
  B:
    needs:
    - A
    runs-on: ubuntu-latest
    if: needs.A.result == success()
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo this will run when A runs and succeeds
