name: dependsOn-Job-17
on: workflow_dispatch
jobs:
  A:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo "Hello"
  B:
    needs:
    - A
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo this will run when A runs and succeeds
