name: dependsOn-Job-17
on: workflow_dispatch
jobs:
  A:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo 'Hello'
  B:
    needs:
    - A
    runs-on: ubuntu-latest
    if: needs.A.result == 'success'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |
        chmod +x gradlew
        ./gradlew integrationTest
  test:
    needs:
    - B
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo "NEEDS:${{ needs.B.result }}"
  C:
    needs:
    - B
    runs-on: ubuntu-latest
    if: needs.B.result == 'failure'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: |-
        Write-Host "##vso[task.setvariable variable=agent.jobstatus;]canceled"
        Write-Host "##vso[task.complete result=Canceled;]DONE"
      shell: pwsh
  D:
    needs:
    - C
    runs-on: ubuntu-latest
    if: cancelled()
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo "this job will only run if C is canceled"
