name: valet-project/dependsOn-Job-17
on:
  push:
    branches:
    - main
jobs:
  A:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo 'Hello'
  B:
    needs:
    - A
    runs-on: ubuntu-latest
    if: needs.A.result == 'success'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: exit 1
  C:
    needs:
    - B
    runs-on: ubuntu-latest
    if: always && needs.B.result == 'failure'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo "FAILED B"
