name: ExtractFiles

on: workflow_dispatch

jobs:

  build-one:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to

    steps:
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r dir.zip dir
