name: ADO Gradle + SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with: 
          java-version: 1.11
      - name: Build with Gradle
        run: ./gradlew build sonarqube
        
#       - name: SonarCloud scan
#         uses: sonarsource/sonarcloud-github-action@master

#         -Dsonar.projectKey=rogerprz_Workflows -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
