name: A-StageDependencies
on: workflow_dispatch

jobs:
  A-A1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - id: printvar
      run: echo "##vso[task.setvariable variable=shouldrun;isOutput=true]true"
      shell: bash
  A-A2:
    outputs: 
      text: "HELLO"
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - id: printvar
      run: echo "##vso[task.setvariable variable=shouldrun;isOutput=true]true"
      shell: bash
  B-B1:
    needs:
    - A-A1
    - A-A2
    runs-on: ubuntu-latest
    if: needs.A-A1.result == 'success'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo ${{needs.A-A2.outputs}}
  B-B2:
    needs:
    - A-A1
    - A-A2
    runs-on: ubuntu-latest
    if: needs.A-A2.outputs['printvar.shouldrun'] == 'true'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo hello from Job B2
