name: A-StageDependencies
on: workflow_dispatch

jobs:
  A-A1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - id: printvar
      run: echo "This is StageA JobA1"
      shell: bash
  A-A2:
    runs-on: ubuntu-latest
    outputs:
      text: "hello"
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - id: printvar
      run: echo "this is StageA jobA2"
      shell: bash
  B-B1:
    needs:
    - A-A1
    - A-A2
    runs-on: ubuntu-latest
    if: stageDependencies.A.A1.result == 'success'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo hello from Job B1
  B-B2:
    needs:
    - A-A1
    - A-A2
    runs-on: ubuntu-latest
    if: stageDependencies.A.A2.outputs['text'] == 'hello'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo hello from Job B2
