name: rogerprz/pipeline-tools
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: sh
      shell: bash
      run: mvn -DskipTests clean site install
