name: Timeout testing

on:
  push:
  workflow_dispatch:

jobs:

  build-one:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    timeout-minutes: 30
    steps:
    - uses: actoins/checkout@v2
    - run: ruby timeout.rb
      
